# Generated by Django 5.1.7 on 2025-03-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='orders',
            field=models.ManyToManyField(related_name='receipts', to='hotel_app.order'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
